# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 10 May 2007 14:37:10 +0200
*               @ALL          1
*               @user         8
*               @admin      255
