<?php 
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: skipper
 * Date: Thu, 31 May 2007 13:44:57 +0200
 */

$conf['title'] = 'Atelier R.L.';
$conf['start'] = 'www:accueil';
$conf['lang'] = 'fr';
$conf['template'] = 'sandy';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['manager'] = '@admin';
$conf['disableactions'] = 'backlink,recent,revisions,resendpwd,profile,subscribe,unsubscribe,source,export_raw';
$conf['htmlok'] = 1;

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content
