<?php
/*
 * Dokuwiki's Local protected Configuration File - Local Settings 
 * generated by sos-web.ch 
 * Run for user: admin
 * Date: Thu, 10 May 2007 14:39:02 +0200
 */

$conf['lang'] = 'fr';
$conf['template'] = 'sandy';
//$conf['template'] = 'default';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
// end auto-generated content
